apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-plugin
  namespace: openshift-gitops
  labels:
    app: gitops-plugin
    app.kubernetes.io/component: gitops-plugin
    app.kubernetes.io/instance: gitops-plugin
    app.kubernetes.io/part-of: gitops-plugin
    app.openshift.io/runtime-namespace: openshift-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-plugin
  template:
    metadata:
      labels:
        app: gitops-plugin
    spec:
      containers:
        - name: gitops-plugin
          image: quay.io/redhat-developer/gitops-console-plugin
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /etc/httpd-ssl/certs/tls.crt
              subPath: tls.crt
            - name: console-serving-cert
              readOnly: true
              mountPath: /etc/httpd-ssl/private/tls.key
              subPath: tls.key
            - name: httpd-cfg
              readOnly: true
              mountPath: /etc/httpd-cfg/httpd.conf
              subPath: httpd.conf
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
        - name: httpd-cfg
          configMap:
            name: httpd-cfg
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-cfg
  namespace: openshift-gitops
  labels:
    app: gitops-plugin
    app.kubernetes.io/part-of: gitops-plugin
data:
  httpd.conf: |
    LoadModule ssl_module modules/mod_ssl.so
    Listen 9001 https
    ServerRoot "/etc/httpd"

    <VirtualHost *:9001>
        DocumentRoot /var/www/html/plugin
        SSLEngine on
        SSLCertificateFile "/etc/httpd-ssl/certs/tls.crt"
        SSLCertificateKeyFile "/etc/httpd-ssl/private/tls.key"
    </VirtualHost>
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: gitops-plugin
  namespace: openshift-gitops
  labels:
    app: gitops-plugin
    app.kubernetes.io/component: gitops-plugin
    app.kubernetes.io/instance: gitops-plugin
    app.kubernetes.io/part-of: gitops-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: gitops-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: gitops-plugin
spec:
  displayName: "GitOps Plugin"
  backend:
    service:
      name: gitops-plugin
      namespace: openshift-gitops
      port: 9001
      basePath: "/"
    type: Service
  i18n:
    loadType: Preload