apiVersion: v1
kind: Namespace
metadata:
  name: console-gitops-plugin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-gitops-plugin
  namespace: console-gitops-plugin
  labels:
    app: console-gitops-plugin
    app.kubernetes.io/component: console-gitops-plugin
    app.kubernetes.io/instance: console-gitops-plugin
    app.kubernetes.io/part-of: console-gitops-plugin
    app.openshift.io/runtime-namespace: console-gitops-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-gitops-plugin
  template:
    metadata:
      labels:
        app: console-gitops-plugin
    spec:
      containers:
        - name: console-gitops-plugin
          image: quay.io/kykchong/console-gitops-plugin:latest
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          args:
            - "--ssl"
            - "--cert=/var/serving-cert/tls.crt"
            - "--key=/var/serving-cert/tls.key"
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
          env:
            - name: SEGMENT_KEY
              value:
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: console-gitops-plugin
  namespace: console-gitops-plugin
  labels:
    app: console-gitops-plugin
    app.kubernetes.io/component: console-gitops-plugin
    app.kubernetes.io/instance: console-gitops-plugin
    app.kubernetes.io/part-of: console-gitops-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: console-gitops-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: console-gitops-plugin
  annotations:
  console.openshift.io/use-i18n: "true"
  # console.openshift.io/default-i18next-namespace: "true"
spec:
  displayName: "Gitops Dynamic Plugin"
  service:
    name: console-gitops-plugin
    namespace: console-gitops-plugin
    port: 9001
    basePath: "/"
  proxy:
    - type: Service
      alias: gitops
      authorize: false
      service:
        name: applications
        namespace: openshift-gitops
        port: 8443
